apiVersion: apps/v1
kind: Deployment
metadata: 
  name: petclinic-deployment
  namespace: default
  labels:
    app: petclinic-spark
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      app: petclinic-spark
  template: 
    metadata:
      labels: 
        app: petclinic-spark
    spec: 
      hostname: petclinic
      subdomain: spark
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers: 
        - name: petclinic-spark
          image: sh827kim/petclinic-spark:1.0
          volumeMounts:
            - mountPath: /logs
              name: log-dir
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources: 
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet: 
              path: /manage/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
      restartPolicy: Always
      terminationGracePeriodSeconds : 30
      volumes:
        - name: log-dir
          hostPath:
            path: /logs

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: default
  labels:
    app: petclinic-spark
spec:
  ports:
  - port: 8080
  selector:
    app: petclinic-spark
  type: ClusterIP 


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http: 
      paths:
        - path: /(.*)
          backend:
            serviceName: petclinic-svc
            servicePort: 8080
